services:
  - type: web
    name: defectoscope
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app:app --timeout 120 --workers 1"
    envVars:
      - key: PORT
        value: 5000
