services:
  - type: web
    name: defectoscope
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app:app --timeout 180 --workers 1 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: 5000
