services:
  - type: web
    name: defectoscope
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: 5000
