services:
  - type: web
    name: pcb-defect-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
